- name: Installing and configuring mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: Copying the mongodb repo file
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: Install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed

  # - name: start and enable mongodb
  #   ansible.builtin.service:
  #     name: mongodb
  #     state: started
  #     enabled: yes