- name: Installing and configuring mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: Copying the mongodb repo file
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: Install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed

  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: replacing listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: restarting the mongod service
    ansible.builtin.service:
      name: mongod
      state: restarted
  